folder: !!str ../ml-100k

#Put {F} instead of the fold number
links:
    test: !!str formated_shufled_u{F}.test
    base: !!str formated_shufled_u{F}.base
    rating_header: !!str rating
    #separator: !!str \t

nodes:
    nodes_meta:
    - gender_id
    nodes_header: !!str userId
    file: !!str formated_users_tmp.dat
    K: !!int 10
    separator: !!str \t

items:
    items_meta:
    - genres_id
    items_header: !!str movieId
    file: !!str formated_movies_tmp.dat
    L: !!int 10
    #separator: !!str \t
    Taus:
    - 10



simulation:
    N_itt: !!int 3000
    N_measure: !!int 1
