folder: !!str ../ml-100k

#Put {F} instead of the fold number
links:
    test: !!str formated_u{F}.test
    base: !!str formated_u{F}.base
    separator_base: !!str ยง
    separator_test: !!str \t
    rating_header: !!str rating

nodes:
    nodes_meta:
    - age_gender_id
    nodes_header: !!str userId
    file: !!str formated_users_tmp2.dat
    K: !!int 10
    separator: !!str \t
    lambda_nodes: 0.01

items:
    #items_meta:
    #- genres_id
    items_header: !!str movieId
    # file: !!str formated_movies_tmp2.dat
    L: !!int 10
    # separator: !!str \t
    # lambda_items: 0.0
    # Taus:
    #- 10

seed: !!int 77777
N_fold: !!int 2

simulation:
    N_itt: !!int 3000
    N_measure: !!int 1
